<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Asp.Versioning.Http" Version="10.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.8" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.8" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Application\JL.Commerce.Tecnology.Service.Application.csproj" />
    <ProjectReference Include="..\Infrastructure.Data\JL.Commerce.Tecnology.Service.Infrastructure.Data.csproj" />
    <ProjectReference Include="..\Infrastructure.Integration\JL.Commerce.Tecnology.Service.Infrastructure.Integration.csproj" />
  </ItemGroup>

</Project>
